# Generated by Django 3.2 on 2021-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_moviepost_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='language',
            field=models.CharField(choices=[('Anh', 'English'), ('Việt', 'VietNam')], max_length=10),
        ),
    ]
