# Generated by Django 3.2 on 2021-04-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_moviepost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='trailer',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
