# Generated by Django 3.2 on 2021-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20210501_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='time_show',
            field=models.CharField(choices=[('9:30', '9:30'), ('11:30', '11:30'), ('13:30', '13:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('18:30', '18:30'), ('20:00', '20:00'), ('21:30', '21:30'), ('23:00', '23:00')], max_length=8),
        ),
    ]
