# Generated by Django 3.2 on 2021-05-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_movieshow_time_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='time_show',
            field=models.TimeField(),
        ),
    ]
