# Generated by Django 3.2 on 2021-04-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='MoviePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('detail', models.TextField(default='')),
                ('cast', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('VIETNAM', 'VietNam')], max_length=10)),
                ('public_date', models.DateTimeField()),
                ('run_length', models.IntegerField(help_text='Enter run length in minutes')),
                ('trailer', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category')),
            ],
            options={
                'verbose_name_plural': 'MoviePost',
            },
        ),
    ]
