# Generated by Django 3.2 on 2021-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='public_date',
            field=models.DateField(),
        ),
    ]
