# Generated by Django 3.2 on 2021-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_moviepost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
