# Generated by Django 3.2 on 2021-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_moviepost_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='trailer',
            field=models.URLField(blank=True),
        ),
    ]
