# Generated by Django 3.2 on 2021-05-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_movieshow_time_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepost',
            name='time',
            field=models.ManyToManyField(to='movie.ShowTime'),
        ),
        migrations.DeleteModel(
            name='MovieShow',
        ),
    ]
